/**
 * Plant to Knowledge mapping
 * Generated by scripts/generate-knowledge.ts
 */

export interface PlantKnowledgeEntry {
  plantName: string;
  articleIds: string[];
  extractedInfo: {
    diseases?: string[];
    pests?: string[];
    careTips?: string[];
    companions?: { plant: string; type: 'good' | 'avoid' }[];
    sowingTime?: string;
    harvestTime?: string;
  };
}

export const PLANT_KNOWLEDGE_MAP: PlantKnowledgeEntry[] = [
  {
    "plantName": "Tomate",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Krautfäule (Phytophthora infestans)",
        "Blütenendfäule",
        "Echter Mehltau",
        "Fusariumwelke",
        "Verticilliumwelke",
        "Grauschimmel (Botrytis)",
        "Bakterienwelke"
      ],
      "pests": [
        "Weiße Fliege",
        "Blattläuse",
        "Spinnmilben",
        "Tomatenminierfliege",
        "Nematoden",
        "Schnecken",
        "Thripse"
      ],
      "careTips": [
        "Regelmäßig und gleichmäßig gießen – am besten morgens direkt an den Wurzelbereich, um Blattnässe zu vermeiden",
        "Ausgeizen: Seitentriebe in den Blattachseln regelmäßig entfernen, um das Wachstum auf die Haupttriebe zu konzentrieren",
        "Stabile Stütze durch Stäbe oder Spiralstangen verwenden und Pflanzen rechtzeitig anbinden",
        "Alle 2–3 Wochen mit einem kaliumbetonten Tomatendünger düngen",
        "Mulchen um die Pflanze herum, um Feuchtigkeit zu speichern und den Boden gleichmäßig warm zu halten",
        "Für gute Durchlüftung sorgen, indem man untere Blätter entfernt"
      ],
      "companions": [
        {
          "plant": "Basilikum",
          "type": "good"
        },
        {
          "plant": "Knoblauch",
          "type": "good"
        },
        {
          "plant": "Karotten",
          "type": "good"
        },
        {
          "plant": "Ringelblume",
          "type": "good"
        },
        {
          "plant": "Sellerie",
          "type": "good"
        },
        {
          "plant": "Petersilie",
          "type": "good"
        },
        {
          "plant": "Kartoffeln",
          "type": "avoid"
        },
        {
          "plant": "Fenchel",
          "type": "avoid"
        },
        {
          "plant": "Kohl",
          "type": "avoid"
        },
        {
          "plant": "Erbsen",
          "type": "avoid"
        }
      ],
      "sowingTime": "März–April (Vorkultur im Haus), Auspflanzung ab Mitte Mai nach den Eisheiligen",
      "harvestTime": "Juli–September, je nach Sorte auch bis Oktober"
    }
  },
  {
    "plantName": "Paprika",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Grauschimmel (Botrytis)",
        "Blütenendfäule",
        "Phytophthora-Fäule",
        "Fusarium-Welke",
        "Mosaikvirus"
      ],
      "pests": [
        "Blattläuse",
        "Spinnmilben",
        "Weiße Fliege",
        "Thripse",
        "Schnecken"
      ],
      "careTips": [
        "Paprika benötigt einen warmen, vollsonnigen und windgeschützten Standort mit mindestens 6 Stunden Sonnenlicht täglich",
        "Regelmäßig gießen, Staunässe vermeiden und den Boden gleichmäßig feucht halten",
        "Alle 2-3 Wochen mit einem kalireichen Dünger düngen, besonders während der Fruchtbildung",
        "Pflanzen regelmäßig ausgeizen und bei Bedarf stützen oder anbinden",
        "Jungpflanzen langsam an Außentemperaturen gewöhnen und erst nach den Eisheiligen ins Freie pflanzen"
      ],
      "companions": [
        {
          "plant": "Tomaten",
          "type": "good"
        },
        {
          "plant": "Basilikum",
          "type": "good"
        },
        {
          "plant": "Karotten",
          "type": "good"
        },
        {
          "plant": "Zwiebeln",
          "type": "good"
        },
        {
          "plant": "Petersilie",
          "type": "good"
        },
        {
          "plant": "Fenchel",
          "type": "avoid"
        },
        {
          "plant": "Kartoffeln",
          "type": "avoid"
        }
      ],
      "sowingTime": "Februar-März (Voranzucht indoor), Auspflanzung ab Mitte Mai",
      "harvestTime": "Juli-Oktober, Früchte können grün geerntet oder vollständig ausgereift (rot, gelb, orange) gepflückt werden"
    }
  },
  {
    "plantName": "Gurke",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Echter Mehltau",
        "Falscher Mehltau",
        "Gurkenmosaikvirus",
        "Wurzelfäule",
        "Bakterielle Welke"
      ],
      "pests": [
        "Spinnmilben",
        "Blattläuse",
        "Gurkenfliege",
        "Weißfliegen",
        "Nematoden"
      ],
      "careTips": [
        "Standort: sonnig und warm mit Temperaturen ab 18°C",
        "Regelmäßig gießen, Staunässe und nasse Blätter vermeiden",
        "Kletterhilfe oder Rankgitter anbieten",
        "Alle 2 Wochen mit Gemüsedünger düngen",
        "Seitentriebe regelmäßig ausbrechen für besseren Ertrag"
      ],
      "companions": [
        {
          "plant": "Bohnen",
          "type": "good"
        },
        {
          "plant": "Erbsen",
          "type": "good"
        },
        {
          "plant": "Dill",
          "type": "good"
        },
        {
          "plant": "Salat",
          "type": "good"
        },
        {
          "plant": "Rote Bete",
          "type": "good"
        },
        {
          "plant": "Kartoffeln",
          "type": "avoid"
        },
        {
          "plant": "Minze",
          "type": "avoid"
        },
        {
          "plant": "Tomaten",
          "type": "avoid"
        }
      ],
      "sowingTime": "März-Mai",
      "harvestTime": "Juli-September"
    }
  },
  {
    "plantName": "Zucchini",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Echter Mehltau",
        "Falscher Mehltau",
        "Grauschimmel (Botrytis)",
        "Virusmosaik",
        "Fusarium-Welke"
      ],
      "pests": [
        "Blattläuse",
        "Spinnmilben",
        "Schnecken",
        "Gurkenkäfer",
        "Weiße Fliege"
      ],
      "careTips": [
        "Regelmäßig und gleichmäßig gießen, Staunässe vermeiden",
        "Mulchen mit Stroh oder Grasschnitt, um Feuchtigkeit zu halten",
        "Alle 2-3 Wochen mit Kompost oder organischen Dünger versorgen",
        "Früchte regelmäßig ernten (bei 15-25 cm), um Nachwuchs zu fördern",
        "Auf gute Luftzirkulation achten, um Pilzkrankheiten vorzubeugen"
      ],
      "companions": [
        {
          "plant": "Bohnen",
          "type": "good"
        },
        {
          "plant": "Mais",
          "type": "good"
        },
        {
          "plant": "Spinat",
          "type": "good"
        },
        {
          "plant": "Radieschen",
          "type": "good"
        },
        {
          "plant": "Dill",
          "type": "good"
        },
        {
          "plant": "Ringelblumen",
          "type": "good"
        },
        {
          "plant": "Kartoffeln",
          "type": "avoid"
        },
        {
          "plant": "Gurken",
          "type": "avoid"
        },
        {
          "plant": "Kürbis",
          "type": "avoid"
        }
      ],
      "sowingTime": "April-Mai (Vorkultur) oder Mai-Juni (Direktsaat ins Freiland)",
      "harvestTime": "Juli-September"
    }
  },
  {
    "plantName": "Karotte",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Möhrenfliegenbefall (Larvenfraß)",
        "Alternaria-Blattfleckenkrankheit",
        "Echter Mehltau",
        "Möhrenschorf",
        "Violette Wurzelfäule",
        "Wurzelhals- und Blattfäule"
      ],
      "pests": [
        "Möhrenfliege",
        "Blattläuse",
        "Nematoden",
        "Drahtwürmer",
        "Schnecken",
        "Möhrenrüsselkäfer"
      ],
      "careTips": [
        "Lockere, tiefgründige und steinfreie Erde verwenden, da Karotten tiefe Wurzeln bilden",
        "Gleichmäßig und regelmäßig gießen, Staunässe und Trockenheit vermeiden",
        "Sämlinge rechtzeitig ausdünnen auf 5-8 cm Abstand",
        "Regelmäßig jäten und flach hacken, um Konkurrenz zu vermeiden",
        "Mulchen mit Grasschnitt oder Stroh, um Feuchtigkeit zu halten und Grünkübel zu reduzieren",
        "Kaliumbetonte Düngung verwenden, frischen Stallmist vermeiden"
      ],
      "companions": [
        {
          "plant": "Zwiebel",
          "type": "good"
        },
        {
          "plant": "Knoblauch",
          "type": "good"
        },
        {
          "plant": "Lauch",
          "type": "good"
        },
        {
          "plant": "Salat",
          "type": "good"
        },
        {
          "plant": "Tomate",
          "type": "good"
        },
        {
          "plant": "Schnittlauch",
          "type": "good"
        },
        {
          "plant": "Dill",
          "type": "avoid"
        },
        {
          "plant": "Rote Bete",
          "type": "avoid"
        },
        {
          "plant": "Petersilie",
          "type": "avoid"
        },
        {
          "plant": "Kartoffel",
          "type": "avoid"
        }
      ],
      "sowingTime": "März-Juli",
      "harvestTime": "Juni-Oktober"
    }
  },
  {
    "plantName": "Möhhre",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Möhrenschwärze (Alternaria-Blattflecken)",
        "Echter Mehltau",
        "Möhrenfäule durch Weichfäule-Bakterien",
        "Stängelbrand",
        "Möhrenrost"
      ],
      "pests": [
        "Möhrenfliege",
        "Nematoden (Wurzelälchen)",
        "Möhrenblattsauger",
        "Schnecken"
      ],
      "careTips": [
        "Lockere, tiefgründige und steinfreie Erde verwenden – Wurzeln wachsen otherwise verkrüppelt",
        "Gleichmäßig feucht halten, Staunässe und Austrocknung vermeiden",
        "Reihen bei 3–5 cm Abstand vereinzeln, damit sich die Wurzeln gut entwickeln",
        "Mulchen mit Grasschnitt oder Stroh hilft Feuchtigkeit zu halten und Unkraut zu unterdrücken",
        "Keine frische organische Düngung direkt vor der Aussaat – gut abgelagerten Kompost verwenden"
      ],
      "companions": [
        {
          "plant": "Zwiebeln",
          "type": "good"
        },
        {
          "plant": "Knoblauch",
          "type": "good"
        },
        {
          "plant": "Lauch",
          "type": "good"
        },
        {
          "plant": "Salat",
          "type": "good"
        },
        {
          "plant": "Erbsen",
          "type": "good"
        },
        {
          "plant": "Dill",
          "type": "good"
        },
        {
          "plant": "Schnittlauch",
          "type": "good"
        },
        {
          "plant": "Rote Bete",
          "type": "avoid"
        },
        {
          "plant": "Pastinake",
          "type": "avoid"
        },
        {
          "plant": "Petersilie",
          "type": "avoid"
        }
      ],
      "sowingTime": "März–Juli",
      "harvestTime": "Juni–Oktober"
    }
  },
  {
    "plantName": "Salat",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Falscher Mehltau",
        "Grauschimmel (Botrytis)",
        "Salatbrand (Marssonina)",
        "Schwarzfleckenkrankheit",
        "Wurzelhals- und Stängelfäule"
      ],
      "pests": [
        "Blattläuse",
        "Schnecken",
        "Salatminierfliege",
        "Erdraupen",
        "Schwarze Bohnenlaus"
      ],
      "careTips": [
        "Salat benötigt gleichmäßige Feuchtigkeit, Staunässe vermeiden",
        "Regelmäßig lockern und Unkraut entfernen",
        "Bei Hitze für Schatten sorgen, um Blütenbildung zu verhindern",
        "Flachwurzler vorsichtig gießen, am besten morgens",
        "Nach dem Auflaufen bei Bedarf vereinzeln"
      ],
      "companions": [
        {
          "plant": "Möhren",
          "type": "good"
        },
        {
          "plant": "Radieschen",
          "type": "good"
        },
        {
          "plant": "Erdbeeren",
          "type": "good"
        },
        {
          "plant": "Schnittlauch",
          "type": "good"
        },
        {
          "plant": "Gurken",
          "type": "good"
        },
        {
          "plant": "Sellerie",
          "type": "good"
        },
        {
          "plant": "Kohl",
          "type": "good"
        },
        {
          "plant": "Petersilie",
          "type": "good"
        },
        {
          "plant": "Fenchel",
          "type": "avoid"
        },
        {
          "plant": "Petersilie (lang stehend)",
          "type": "avoid"
        }
      ],
      "sowingTime": "März-September (Reihensaat), Januar-März (Vorkultur unter Glas)",
      "harvestTime": "Mai-Oktober (je nach Sorte und Aussaatzeit)"
    }
  },
  {
    "plantName": "Spinat",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Falscher Mehltau",
        "Blattfleckenkrankheit",
        "Wurzelfäule",
        "Mosaikvirus"
      ],
      "pests": [
        "Blattläuse",
        "Erdflöhe",
        "Schnecken",
        "Spinnmilben",
        "Minierfliegen"
      ],
      "careTips": [
        "Spinat benötigt einen humusreichen, feuchten und gut durchlässigen Boden an einem halbschattigen bis sonnigen Standort",
        "Regelmäßig und gleichmäßig gießen, Staunässe und Trockenheit vermeiden, da beides zu Schosserbildung führt",
        "Dünn aussäen mit einem Reihenabstand von etwa 20-30 cm, da enger Standort Pilzkrankheiten begünstigt",
        "Mulchen mit Grasschnitt oder Stroh hilft die Feuchtigkeit zu halten und Unkraut zu unterdrücken",
        "Schnell ernten, sobald die Blätter groß genug sind, da Spinat bei zu später Ernte schnell schosst"
      ],
      "companions": [
        {
          "plant": "Erdbeeren",
          "type": "good"
        },
        {
          "plant": "Möhren",
          "type": "good"
        },
        {
          "plant": "Radieschen",
          "type": "good"
        },
        {
          "plant": "Kohl",
          "type": "good"
        },
        {
          "plant": "Salat",
          "type": "good"
        },
        {
          "plant": "Stangenbohnen",
          "type": "good"
        },
        {
          "plant": "Kartoffeln",
          "type": "avoid"
        }
      ],
      "sowingTime": "März-Mai und August-September",
      "harvestTime": "April-Juni und Oktober-November"
    }
  },
  {
    "plantName": "Erbse",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Echter Mehltau (Erysiphe pisi)",
        "Falscher Mehltau (Peronospora pisi)",
        "Brennfleckenkrankheit (Ascochyta pisi)",
        "Wurzelhals- und Fußfäule (Fusarium spp.)",
        "Grauschimmel (Botrytis cinerea)"
      ],
      "pests": [
        "Erbsenblattlaus (Acyrthosiphon pisum)",
        "Erbsenkäfer (Bruchus pisorum)",
        "Erbsenwickler (Cydia nigricana)",
        "Nematoden",
        "Spinnmilben"
      ],
      "careTips": [
        "Erbsen an sonnigen bis halbschattigen Standort mit lockeren, tiefgründigen Böden aussäen",
        "Saatgut ca. 3-5 cm tief und in Reihen mit 30-40 cm Abstand legen",
        "Rankhilfe (Stäbe, Netz oder Gitter) anbieten, damit die Pflanzen Halt finden",
        "Gleichmäßig feucht halten, Staunässe unbedingt vermeiden",
        "Regelmäßig jäten und bei Trockenheit gießen, Mulchschicht hilft bei Feuchtigkeitsspeicherung",
        "Erbsen sind Kohlendioxid-Produzenten und reichern den Boden mit Stickstoff an"
      ],
      "companions": [
        {
          "plant": "Möhre",
          "type": "good"
        },
        {
          "plant": "Radieschen",
          "type": "good"
        },
        {
          "plant": "Kohl",
          "type": "good"
        },
        {
          "plant": "Gurke",
          "type": "good"
        },
        {
          "plant": "Dill",
          "type": "good"
        },
        {
          "plant": "Spinat",
          "type": "good"
        },
        {
          "plant": "Mais",
          "type": "good"
        },
        {
          "plant": "Zwiebel",
          "type": "avoid"
        },
        {
          "plant": "Knoblauch",
          "type": "avoid"
        },
        {
          "plant": "Tomate",
          "type": "avoid"
        },
        {
          "plant": "Fenchel",
          "type": "avoid"
        },
        {
          "plant": "Schnittlauch",
          "type": "avoid"
        }
      ],
      "sowingTime": "März-Mai (Direktsaat ins Freiland, verträgt leichte Fröste bis -5°C)",
      "harvestTime": "Juni-August (je nach Sorte und Aussaatzeitpunkt, ca. 60-90 Tage nach Aussaat)"
    }
  },
  {
    "plantName": "Bohne",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Brennfleckenkrankheit (Colletotrichum lindemuthianum)",
        "Fettfleckenkrankheit (Pseudomonas syringae)",
        "Bohnenmosaikvirus (BCMV)",
        "Wurzelfäule (Fusarium spp.)",
        "Rost (Uromyces appendiculatus)"
      ],
      "pests": [
        "Schwarze Bohnenlaus (Aphis fabae)",
        "Bohnenfliege (Delia platura)",
        "Spinnmilben (Tetranychidae)",
        "Schnecken (Gastropoda)",
        "Mexikanische Bohnenblattlaus (Aphis craccivora)"
      ],
      "careTips": [
        "Aussaat erst nach den Eisheiligen Mitte Mai, da Bohnen frostempfindlich sind",
        "Regelmäßig gießen, besonders während der Blüte und Hülsenbildung, aber Staunässe vermeiden",
        "Rankende Sorten benötigen eine Stütze oder Rankhilfe",
        "Auf trockene Blätter achten, um Pilzkrankheiten vorzubeugen",
        "Ernten Sie regelmäßig, um die Pflanze zur weiteren Produktion anzuregen",
        "Lockern Sie den Boden regelmäßig, um Durchlüftung zu gewährleisten"
      ],
      "companions": [
        {
          "plant": "Mais",
          "type": "good"
        },
        {
          "plant": "Kürbis",
          "type": "good"
        },
        {
          "plant": "Gurke",
          "type": "good"
        },
        {
          "plant": "Kartoffel",
          "type": "good"
        },
        {
          "plant": "Sellerie",
          "type": "good"
        },
        {
          "plant": "Zwiebel",
          "type": "avoid"
        },
        {
          "plant": "Knoblauch",
          "type": "avoid"
        },
        {
          "plant": "Fenchel",
          "type": "avoid"
        },
        {
          "plant": "Erbsen",
          "type": "avoid"
        }
      ],
      "sowingTime": "Mai-Juni",
      "harvestTime": "Juli-September"
    }
  },
  {
    "plantName": "Kartoffel",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Krautfäule (Phytophthora infestans)",
        "Kartoffelschorf (Streptomyces scabies)",
        "Rhizoctonia (Rhizoctonia solani)",
        "Schwarzbeinigkeit (Erwinia carotovora)",
        "Kartoffelvirus Y (PVY)"
      ],
      "pests": [
        "Kartoffelkäfer (Leptinotarsa decemlineata)",
        "Drahtwürmer (Elateridae)",
        "Kartoffelzystennematoden (Globodera rostochiensis)",
        "Blattläuse (Aphidoidea)",
        "Schnecken (Gastropoda)"
      ],
      "careTips": [
        "Kartoffeln an einem sonnigen Standort mit lockeren, nährstoffreichen Böden pflanzen",
        "Pflanzzeit ist ab April, sobald die Bodentemperatur mindestens 8°C erreicht hat",
        "Kartoffeln etwa 8-10 cm tief pflanzen und regelmäßig anhäufeln, um die Knollenbildung zu fördern",
        "Gleichmäßig wässern, jedoch Staunässe und übermäßige Feuchtigkeit vermeiden",
        "Vor dem Pflanzen vorgekeimte Kartoffeln verwenden für einen schnelleren und kräftigeren Wachstumsstart",
        "Nach der Blüte das Gießen reduzieren, um Fäulnis zu vermeiden und die Schalenfestigkeit zu fördern"
      ],
      "companions": [
        {
          "plant": "Bohnen",
          "type": "good"
        },
        {
          "plant": "Meerrettich",
          "type": "good"
        },
        {
          "plant": "Spinat",
          "type": "good"
        },
        {
          "plant": "Kapuzinerkresse",
          "type": "good"
        },
        {
          "plant": "Kohl",
          "type": "good"
        },
        {
          "plant": "Tomaten",
          "type": "avoid"
        },
        {
          "plant": "Sonnenblumen",
          "type": "avoid"
        },
        {
          "plant": "Gurken",
          "type": "avoid"
        },
        {
          "plant": "Sellerie",
          "type": "avoid"
        }
      ],
      "sowingTime": "März-Mai (Vorkeimung ab Februar, Pflanzung ab April)",
      "harvestTime": "Juli-September (Frühkartoffeln ab Juli, Lagerkartoffeln ab September)"
    }
  },
  {
    "plantName": "Zwiebel",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Falscher Mehltau (Peronospora destructor)",
        "Zwiebelrost (Puccinia porri)",
        "Grauschimmelfäule (Botrytis allii)",
        "Zwiebelhalsfäule",
        "Bakterielle Blattfleckenkrankheit"
      ],
      "pests": [
        "Zwiebelfliege (Delia antiqua)",
        "Thripse (Thysanoptera)",
        "Zwiebelmilbe (Rhizoglyphus echinopus)",
        "Stängelälchen (Ditylenchus dipsaci)",
        "Zwiebelzirpe"
      ],
      "careTips": [
        "Zwiebeln an einem sonnigen Standort mit lockerm, humusreichem Boden pflanzen",
        "Regelmäßig gießen, jedoch Staunässe vermeiden – Zwiebeln vertragen Trockenheit besser als zu viel Nässe",
        "Boden regelmäßig hacken und Unkraut entfernen, um Konkurrenz zu vermeiden",
        "Zwiebeln nicht zu tief pflanzen – die Zwiebel sollte nur leicht mit Erde bedeckt sein",
        "Auf ausreichende Kalium- und Phosphatversorgung achten, Stickstoffgaben moderat halten",
        "Nach dem Einziehen des Laubes die Zwiebeln bei trockenem Wetter ernten und nachtrocknen lassen"
      ],
      "companions": [
        {
          "plant": "Möhre",
          "type": "good"
        },
        {
          "plant": "Tomate",
          "type": "good"
        },
        {
          "plant": "Kopfsalat",
          "type": "good"
        },
        {
          "plant": "Erdbeere",
          "type": "good"
        },
        {
          "plant": "Kamille",
          "type": "good"
        },
        {
          "plant": "Rote Bete",
          "type": "good"
        },
        {
          "plant": "Erbsen",
          "type": "avoid"
        },
        {
          "plant": "Bohnen",
          "type": "avoid"
        },
        {
          "plant": "Weißkohl",
          "type": "avoid"
        }
      ],
      "sowingTime": "März-Mai (Direktsaat) oder Februar-März (Vorkultur im Haus)",
      "harvestTime": "Juli-September"
    }
  },
  {
    "plantName": "Knoblauch",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Knoblauchrost (Puccinia allii)",
        "Falscher Mehltau (Peronospora destructor)",
        "Weißfäule (Sclerotium cepivorum)",
        "Bakterielle Weichfäule",
        "Knoblauchschimmel (Aspergillus niger)"
      ],
      "pests": [
        "Zwiebelfliege (Delia antiqua)",
        "Thripse (Thysanoptera)",
        "Stängelnematoden (Ditylenchus dipsaci)",
        "Zwiebelmilbe (Rhizoglyphus echinopus)",
        "Lauchmotte (Acrolepiopsis assectella)"
      ],
      "careTips": [
        "Knoblauch an einen sonnigen Standort mit gut durchlässigem Boden pflanzen",
        "Zehen ca. 5-8 cm tief und 10-15 cm voneinander entfernt stecken",
        "Regelmäßig gießen, aber Staunässe vermeiden",
        "Mulchen hilft, Feuchtigkeit zu halten und Unkraut zu unterdrücken",
        "Blütensamen frühzeitig entfernen, um größere Zehen zu fördern",
        "Vor der Ernte das Gießen einstellen",
        "Leichte Stickstoffdüngung im Frühjahr, dann nicht mehr düngen"
      ],
      "companions": [
        {
          "plant": "Tomaten",
          "type": "good"
        },
        {
          "plant": "Erdbeeren",
          "type": "good"
        },
        {
          "plant": "Möhren",
          "type": "good"
        },
        {
          "plant": "Rote Bete",
          "type": "good"
        },
        {
          "plant": "Kohl",
          "type": "good"
        },
        {
          "plant": "Gurken",
          "type": "good"
        },
        {
          "plant": "Bohnen",
          "type": "avoid"
        },
        {
          "plant": "Erbsen",
          "type": "avoid"
        }
      ],
      "sowingTime": "Oktober-November (Winterknoblauch) oder März-Mai (Frühlingsknoblauch)",
      "harvestTime": "Juli-September"
    }
  },
  {
    "plantName": "Lauch",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Lauchrost (Puccinia porri)",
        "Falscher Mehltau (Peronospora destructor)",
        "Bakterielle Weichfäule",
        "Virosen (Vergilbungsviren)"
      ],
      "pests": [
        "Lauchmotte (Acrolepiopsis assectella)",
        "Zwiebelfliege (Delia antiqua)",
        "Thrips (Thrips tabaci)",
        "Lauchblattlaus (Myzus ascalonicus)",
        "Stängelälchen (Ditylenchus dipsaci)"
      ],
      "careTips": [
        "Regelmäßig und gleichmäßig gießen, Staunässe vermeiden",
        "Pflanzen regelmäßig anhäufeln für längere weiße Schäfte",
        "Boden lockern und Unkraut entfernen für gute Durchlüftung",
        "Organischen Dünger oder Kompost vor der Pflanzung einarbeiten",
        "Mulchen hilft, Feuchtigkeit zu halten und Unkraut zu unterdrücken"
      ],
      "companions": [
        {
          "plant": "Möhren",
          "type": "good"
        },
        {
          "plant": "Sellerie",
          "type": "good"
        },
        {
          "plant": "Erdbeeren",
          "type": "good"
        },
        {
          "plant": "Tomaten",
          "type": "good"
        },
        {
          "plant": "Zwiebeln",
          "type": "good"
        },
        {
          "plant": "Bohnen",
          "type": "avoid"
        },
        {
          "plant": "Erbsen",
          "type": "avoid"
        }
      ],
      "sowingTime": "Februar-März (Voranzucht), April-Mai (Direktsaat)",
      "harvestTime": "September-März (je nach Sorte und Anbauzeitpunkt)"
    }
  },
  {
    "plantName": "Kohl",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Kohlhernie",
        "Falscher Mehltau",
        "Schwarzbeinkrankheit",
        "Alternaria",
        "Xanthomonas-Blattflecken"
      ],
      "pests": [
        "Kohlweißling",
        "Kohlfliege",
        "Blattläuse",
        "Kohlerdflöhe",
        "Thripse"
      ],
      "careTips": [
        "Kohl benötigt gleichmäßige und reichliche Bewässerung, besonders bei Kopfbildung, um Rissen vorzubeugen.",
        "Regelmäßiges Hacken und Mulchen fördert die Wasserspeicherung und unterdrückt Unkraut.",
        "Stickstoffreiche Düngung vor dem Pflanzen und eine Nachdüngung während des Wachstums unterstützen kräftige Köpfe.",
        "Um Kohlhernie zu vermeiden, sollte eine Fruchtfolge von mindestens 4 Jahren mit Kreuzblütlern eingehalten werden.",
        "Netze schützen die Pflanzen effektiv vor Schädlingen wie Kohlweißling und Kohlfliege."
      ],
      "companions": [
        {
          "plant": "Dill",
          "type": "good"
        },
        {
          "plant": "Sellerie",
          "type": "good"
        },
        {
          "plant": "Bohnen",
          "type": "good"
        },
        {
          "plant": "Spinat",
          "type": "good"
        },
        {
          "plant": "Tomaten",
          "type": "good"
        },
        {
          "plant": "Erdbeeren",
          "type": "avoid"
        },
        {
          "plant": "Andere Kohlgewächse",
          "type": "avoid"
        },
        {
          "plant": "Senf",
          "type": "avoid"
        },
        {
          "plant": "Rettich",
          "type": "avoid"
        }
      ],
      "sowingTime": "Februar-April (Vorkultur), Mai-Juni (Direktsaat)",
      "harvestTime": "Juni-Oktober je nach Sorte und Pflanzzeit"
    }
  },
  {
    "plantName": "Brokkoli",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Kohlhernie (Plasmodiophora brassicae)",
        "Falscher Mehltau (Peronospora parasitica)",
        "Alternaria-Blattflecken (Alternaria brassicae)",
        "Schwarzfäule (Xanthomonas campestris)",
        "Rapsschwärze (Leptosphaeria maculans)"
      ],
      "pests": [
        "Kohlfliege (Delia radicum)",
        "Kohlweißling (Pieris brassicae)",
        "Kohlmotte (Plutella xylostella)",
        "Blattläuse (Aphididae)",
        "Erdflöhe (Phyllotreta)",
        "Schnecken (Gastropoda)"
      ],
      "careTips": [
        "Brokkoli benötigt einen sonnigen bis halbschattigen Standort mit nährstoffreichem, feuchtem Boden",
        "Regelmäßiges Gießen ist wichtig, besonders bei Trockenheit – der Boden sollte gleichmäßig feucht gehalten werden",
        "Eine Mulchschicht hilft, die Feuchtigkeit im Boden zu halten und Unkraut zu unterdrücken",
        "Regelmäßige Düngung mit Stickstoff-reichem Dünger fördert das Wachstum der Köpfe",
        "Nach der ersten Ernte des Hauptkopfes können sich Seitentriebe entwickeln, die ebenfalls geerntet werden können",
        "Pflanzabstand von ca. 50x50 cm einhalten für ausreichende Belüftung",
        "Nachbarpflanzen wie Sellerie oder Tomaten können Schädlinge abwehren"
      ],
      "companions": [
        {
          "plant": "Sellerie",
          "type": "good"
        },
        {
          "plant": "Tomaten",
          "type": "good"
        },
        {
          "plant": "Thymian",
          "type": "good"
        },
        {
          "plant": "Ringelblume",
          "type": "good"
        },
        {
          "plant": "Spinat",
          "type": "good"
        },
        {
          "plant": "Kartoffeln",
          "type": "good"
        },
        {
          "plant": "Erdbeeren",
          "type": "good"
        },
        {
          "plant": "Andere Kohlarten",
          "type": "avoid"
        },
        {
          "plant": "Zwiebeln",
          "type": "avoid"
        },
        {
          "plant": "Knoblauch",
          "type": "avoid"
        },
        {
          "plant": "Radieschen",
          "type": "avoid"
        }
      ],
      "sowingTime": "Februar-April (Vorkultur im Haus) oder April-Mai (Direktsaat im Freiland)",
      "harvestTime": "Juni-Oktober, je nach Sorte und Aussaattermin"
    }
  },
  {
    "plantName": "Blumenkohl",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Kohlhernie (Plasmodiophora brassicae)",
        "Falscher Mehltau (Peronospora parasitica)",
        "Schwarzbeinigkeit (Pythium spp.)",
        "Alternaria (Alternaria brassicae)",
        "Bakterielle Weichfäule (Erwinia carotovora)"
      ],
      "pests": [
        "Kohlfliege (Delia radicum)",
        "Kohlweißling (Pieris brassicae)",
        "Kohlblattlaus (Brevicoryne brassicae)",
        "Kohlmotten (Plutella xylostella)",
        "Erdflöhe (Phyllotreta spp.)",
        "Thripse"
      ],
      "careTips": [
        "Regelmäßig und gleichmäßig gießen, besonders während der Kopfentwicklung – unregelmäßige Wasserversorgung führt zu 'Buttoning' (vorzeitiges Schossen)",
        "Boden mit Kompost anreichern und auf einen pH-Wert von 6,0–7,0 achten, um Kohlhernie vorzubeugen",
        "Junge Köpfe mit eigenen Blättern oder einem Lichtschutzschild abdecken, damit sie schön weiß und zart bleiben (Bleichen)",
        "Alle 3–4 Wochen mit stickstoffreichem Dünger versorgen, da Blumenkohl ein Starkzehrer ist",
        "Mulchen, um den Boden kühl und feucht zu halten, besonders bei Sommeranbau"
      ],
      "companions": [
        {
          "plant": "Sellerie",
          "type": "good"
        },
        {
          "plant": "Spinat",
          "type": "good"
        },
        {
          "plant": "Dill",
          "type": "good"
        },
        {
          "plant": "Kartoffeln",
          "type": "good"
        },
        {
          "plant": "Zwiebeln",
          "type": "good"
        },
        {
          "plant": "Rote Bete",
          "type": "good"
        },
        {
          "plant": "Tomaten",
          "type": "avoid"
        },
        {
          "plant": "Erdbeeren",
          "type": "avoid"
        },
        {
          "plant": "Andere Kohlgewächse (Kreuzblütler)",
          "type": "avoid"
        }
      ],
      "sowingTime": "Februar-Mai (Vorkultur) oder Direktsaat ab April",
      "harvestTime": "Juni-Oktober je nach Sorte und Aussaattermin"
    }
  },
  {
    "plantName": "Radieschen",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Kohlhernie",
        "Falscher Mehltau",
        "Schwarzfleckigkeit",
        "Radieschenfäule"
      ],
      "pests": [
        "Kohlfliege",
        "Erdflöhe",
        "Blattläuse",
        "Schnecken"
      ],
      "careTips": [
        "Regelmäßig und gleichmäßig gießen, da Trockenheit zu pelzigen und scharfen Radieschen führt",
        "In lockere, humusreiche Erde säen und nicht zu tief einarbeiten (ca. 1 cm)",
        "Dünnen Sie die Sämlinge auf 3-5 cm Abstand aus, um schöne Knollen zu erhalten",
        "Vermeiden Sie Staunässe, sorgen Sie aber für gleichmäßige Feuchtigkeit",
        "Ernten Sie rechtzeitig, da Radieschen bei zu später Ernte holzig und pelzig werden"
      ],
      "companions": [
        {
          "plant": "Salat",
          "type": "good"
        },
        {
          "plant": "Spinat",
          "type": "good"
        },
        {
          "plant": "Karotten",
          "type": "good"
        },
        {
          "plant": "Bohnen",
          "type": "good"
        },
        {
          "plant": "Erbsen",
          "type": "good"
        },
        {
          "plant": "Gurken",
          "type": "avoid"
        },
        {
          "plant": "Zucchini",
          "type": "avoid"
        },
        {
          "plant": "Kohl",
          "type": "avoid"
        }
      ],
      "sowingTime": "März-September",
      "harvestTime": "April-Oktober"
    }
  },
  {
    "plantName": "Rettich",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Kohlhernie (Plasmodiophora brassicae)",
        "Rettichschwärze (Alternaria brassicae)",
        "Falscher Mehltau (Peronospora parasitica)",
        "Bakterielle Weichfäule (Erwinia carotovora)"
      ],
      "pests": [
        "Kohlfliege (Delia radicum)",
        "Blattläuse (Aphidoidea)",
        "Schnecken (Gastropoda)",
        "Kohleule (Mamestra brassicae)",
        "Flohkäfer (Phyllotreta)"
      ],
      "careTips": [
        "Lockere, tiefgründige und humusreiche Erde verwenden, um eine ungestörte Wurzelentwicklung zu ermöglichen",
        "Gleichmäßig feucht halten, besonders während der Knollenbildung – Trockenheit führt zu pelzigen und scharfen Rettichen",
        "Regelmäßig hacken und Unkraut entfernen, um Konkurrenz zu vermeiden und die Bodenbelüftung zu fördern",
        "Flach säen (ca. 1-2 cm tief) und Pflanzabstand von 25-30 cm einhalten",
        "Überdüngung mit Stickstoff vermeiden, da dies zu üppigem Blattwachstum auf Kosten der Knollen führt",
        "Schattierung bei Sommerrettich vermeiden – sonniger Standort fördert gesundes Wachstum"
      ],
      "companions": [
        {
          "plant": "Möhren",
          "type": "good"
        },
        {
          "plant": "Salat",
          "type": "good"
        },
        {
          "plant": "Spinat",
          "type": "good"
        },
        {
          "plant": "Erbsen",
          "type": "good"
        },
        {
          "plant": "Bohnen",
          "type": "good"
        },
        {
          "plant": "Zwiebeln",
          "type": "good"
        },
        {
          "plant": "Gurken",
          "type": "good"
        },
        {
          "plant": "Kohl",
          "type": "avoid"
        },
        {
          "plant": "Radieschen",
          "type": "avoid"
        }
      ],
      "sowingTime": "März-Mai (Frührettich) und Juli-August (Herbstrettich/Winterrettich)",
      "harvestTime": "April-Juni (Frührettich) und September-Oktober (Winterrettich)"
    }
  },
  {
    "plantName": "Rote Bete",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Cercospora-Blattfleckenkrankheit",
        "Echter Mehltau",
        "Wurzelfäule",
        "Rhabdomyolyse"
      ],
      "pests": [
        "Blattläuse",
        "Minierfliegen",
        "Rübenfliege",
        "Nematoden",
        "Drahtwürmer"
      ],
      "careTips": [
        "Gleichmäßig gießen, Staunässe vermeiden",
        "Pflanzabstand von ca. 25-30 cm einhalten",
        "Boden lockern und unkrautfrei halten",
        "Junge Pflänzchen frühzeitig vereinzeln (ausdünnen)",
        "Flachwurzler nicht tief hacken"
      ],
      "companions": [
        {
          "plant": "Zwiebeln",
          "type": "good"
        },
        {
          "plant": "Buschbohnen",
          "type": "good"
        },
        {
          "plant": "Kohlgewächse",
          "type": "good"
        },
        {
          "plant": "Salat",
          "type": "good"
        },
        {
          "plant": "Spinat",
          "type": "good"
        },
        {
          "plant": "Stangenbohnen",
          "type": "avoid"
        },
        {
          "plant": "Mangold",
          "type": "avoid"
        },
        {
          "plant": "Gartenmelde",
          "type": "avoid"
        }
      ],
      "sowingTime": "April-Mai (Direktsaat ins Freiland)",
      "harvestTime": "Juli-Oktober"
    }
  },
  {
    "plantName": "Mangold",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Falscher Mehltau",
        "Cercospora-Blattfleckenkrankheit",
        "Rhabarber-Wurzelfäule",
        "Mangoldmosaikvirus"
      ],
      "pests": [
        "Blattläuse",
        "Minierfliegen",
        "Schnecken",
        "Rettichfliege"
      ],
      "careTips": [
        "Mangold benötigt gleichmäßige Feuchtigkeit – regelmäßig gießen, Staunässe vermeiden",
        "Mehrfache Ernte durch Abschneiden der äußeren Blätter ermöglicht längere Ertragszeit",
        "Tief gelockerten, nährstoffreichen Boden bieten und während der Wachstumsphase mit Kompost düngen",
        "Mulchen hilft, Feuchtigkeit zu halten und Unkraut zu unterdrücken",
        "An sonnigen bis halbschattigen Standort pflanzen"
      ],
      "companions": [
        {
          "plant": "Bohnen",
          "type": "good"
        },
        {
          "plant": "Kohl",
          "type": "good"
        },
        {
          "plant": "Rote Bete",
          "type": "good"
        },
        {
          "plant": "Zwiebeln",
          "type": "good"
        },
        {
          "plant": "Sellerie",
          "type": "good"
        },
        {
          "plant": "Salat",
          "type": "good"
        },
        {
          "plant": "Spinat",
          "type": "avoid"
        },
        {
          "plant": "Möhren",
          "type": "avoid"
        }
      ],
      "sowingTime": "März-Mai (Direktsaat) oder Juli-August (Nachfolgkultur)",
      "harvestTime": "Juni-Oktober"
    }
  },
  {
    "plantName": "Zuckermais",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Maisrost (Puccinia sorghi)",
        "Fusarium-Fuß- und Kolbenfäule",
        "Bakterielle Welke (Pantoea stewartii)",
        "Maisbeulenbrand (Ustilago maydis)",
        "Graue Blattfleckenkrankheit (Cercospora zeae-maydis)"
      ],
      "pests": [
        "Maiszünsler (Ostrinia nubilalis)",
        "Maiswurzelbohrer",
        "Blattläuse (verschiedene Arten)",
        "Drahtwürmer (Agriotes spp.)",
        "Stängelbohrer",
        "Feldmaus"
      ],
      "careTips": [
        "Aussaat ab April direkt ins Freiland, Saattiefe ca. 2-3 cm",
        "Standort in voller Sonne wählen, mindestens 6 Stunden Sonnenlicht pro Tag",
        "Regelmäßig und gleichmäßig gießen, besonders während der Blüte und Kolbenentwicklung",
        "Mulchen um die Pflanzen, um Feuchtigkeit zu halten und Unkraut zu unterdrücken",
        "Düngung mit stickstoffreichem Dünger während des Wachstums",
        "Pflanzen in Blöcken säen (mindestens 4 Reihen nebeneinander) für bessere Bestäubung",
        "Reihabstand ca. 70-80 cm, Pflanzenabstand ca. 20-25 cm einhalten"
      ],
      "companions": [
        {
          "plant": "Stangenbohnen",
          "type": "good"
        },
        {
          "plant": "Zucchini",
          "type": "good"
        },
        {
          "plant": "Gurken",
          "type": "good"
        },
        {
          "plant": "Kürbis",
          "type": "good"
        },
        {
          "plant": "Erbsen",
          "type": "good"
        },
        {
          "plant": "Kartoffeln",
          "type": "good"
        },
        {
          "plant": "Tomaten",
          "type": "avoid"
        },
        {
          "plant": "Sellerie",
          "type": "avoid"
        }
      ],
      "sowingTime": "April-Mai (direkte Aussaat im Freiland) oder April (Vorkultur in Töpfen)",
      "harvestTime": "Juli-September, ca. 60-90 Tage nach Aussaat"
    }
  },
  {
    "plantName": "Kürbis",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Echter Mehltau",
        "Falscher Mehltau",
        "Kürbis-Virus (ZYMV)",
        "Fusarium-Wurzelfäule",
        "Blattfleckenkrankheit"
      ],
      "pests": [
        "Gurkenkäfer",
        "Blattläuse",
        "Spinnmilben",
        "Schnecken",
        "Kürbisrüssler"
      ],
      "careTips": [
        "Sonniger, warmer Standort mit nährstoffreichem, gut durchlässigem Boden",
        "Regelmäßig und gleichmäßig gießen, Staunässe vermeiden",
        "Mulchen mit Stroh oder Grasschnitt, um Feuchtigkeit zu halten und Früchte vor Fäulnis zu schützen",
        "Ausreichend Platz einplanen (1-2 m² pro Pflanze)",
        "Regelmäßig mit Kompost oder organischen Dünger düngen",
        "Fruchtfolge von 3-4 Jahren einhalten"
      ],
      "companions": [
        {
          "plant": "Mais",
          "type": "good"
        },
        {
          "plant": "Stangenbohnen",
          "type": "good"
        },
        {
          "plant": "Dill",
          "type": "good"
        },
        {
          "plant": "Radieschen",
          "type": "good"
        },
        {
          "plant": "Ringelblumen",
          "type": "good"
        },
        {
          "plant": "Kartoffeln",
          "type": "avoid"
        },
        {
          "plant": "Andere Kürbisgewächse",
          "type": "avoid"
        }
      ],
      "sowingTime": "April (Vorkultur) oder Mai-Juni (Direktsaat)",
      "harvestTime": "September-Oktober"
    }
  },
  {
    "plantName": "Melone",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Echter Mehltau",
        "Fusarium-Welke",
        "Mosaikvirus",
        "Gurkenfäule (Phytophthora)"
      ],
      "pests": [
        "Melonengallmücke",
        "Blattläuse",
        "Spinnmilben",
        "Gurkenkäfer"
      ],
      "careTips": [
        "Standort: sonnig, warm und windgeschützt wählen",
        "Regelmäßig gießen, Staunässe vermeiden",
        "Mulchen mit Stroh zur Feuchtigkeitsspeicherung",
        "Alle 2 Wochen mit Gemüsedünger düngen",
        "Jungpflanzen bei Kälte mit Vlies abdecken"
      ],
      "companions": [
        {
          "plant": "Mais",
          "type": "good"
        },
        {
          "plant": "Ringelblume",
          "type": "good"
        },
        {
          "plant": "Radieschen",
          "type": "good"
        },
        {
          "plant": "Kartoffeln",
          "type": "avoid"
        }
      ],
      "sowingTime": "April-Mai (Vorkultur), Mai-Juni (Direktsaat)",
      "harvestTime": "Juli-September"
    }
  },
  {
    "plantName": "Erdbeere",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Grauschimmel (Botrytis cinerea)",
        "Echter Mehltau",
        "Wurzelfäule (Phytophthora)",
        "Blattfleckenkrankheit",
        "Verticillium-Welke"
      ],
      "pests": [
        "Erdbeermilben",
        "Blattläuse",
        "Schnecken",
        "Erdbeerblütenstecher",
        "Spinnmilben",
        "Drahtwürmer"
      ],
      "careTips": [
        "Standort: sonnig bis halbschattig mit humusreichem, leicht saurem Boden (pH 5.5-6.5)",
        "Regelmäßig gießen, besonders während der Fruchtbildung, Staunässe vermeiden",
        "Boden mit Stroh mulchen, um Früchte vor Fäulnis zu schützen und Feuchtigkeit zu halten",
        "Im Frühjahr mit reifem Kompost oder Beerendünger düngen",
        "Ausläufer regelmäßig entfernen, um die Kraft der Mutterpflanze zu erhalten",
        "Nach der Ernte Laub bodennah zurückschneiden und Pflanzen vereinzeln"
      ],
      "companions": [
        {
          "plant": "Spinat",
          "type": "good"
        },
        {
          "plant": "Knoblauch",
          "type": "good"
        },
        {
          "plant": "Zwiebeln",
          "type": "good"
        },
        {
          "plant": "Borretsch",
          "type": "good"
        },
        {
          "plant": "Schnittlauch",
          "type": "good"
        },
        {
          "plant": "Tagetes",
          "type": "good"
        },
        {
          "plant": "Kartoffeln",
          "type": "avoid"
        },
        {
          "plant": "Tomaten",
          "type": "avoid"
        },
        {
          "plant": "Kohl",
          "type": "avoid"
        },
        {
          "plant": "Minze (unkontrolliert)",
          "type": "avoid"
        }
      ],
      "sowingTime": "Februar-März (Aussaat unter Glas) oder März-Mai (Pflanzung von Jungpflanzen/Ausläufern)",
      "harvestTime": "Juni-September (je nach Sorte und Pflanzzeit)"
    }
  },
  {
    "plantName": "Himbeere",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Grauschimmel (Botrytis cinerea)",
        "Rutensterben (Didymella applanata)",
        "Himbeerrost (Pucciniastrum idaei)",
        "Phytophthora-Wurzelfäule",
        "Himbeermosaikvirus"
      ],
      "pests": [
        "Himbeerkäfer (Byturus tomentosus)",
        "Himbeerblütenstecher (Anthonomus rubi)",
        "Spinnmilben",
        "Blattläuse",
        "Himbeerruten-Gallmücke"
      ],
      "careTips": [
        "Regelmäßig gießen, besonders während der Fruchtbildung und bei Trockenheit",
        "Jährlich die abgetragenen Ruten bodennah zurückschneiden",
        "Mulchen mit Stroh oder Rindenmulch zur Feuchtigkeitsregulierung",
        "Rankhilfen oder Drahtgerüste verwenden, um die Ruten zu stützen",
        "Organischen Dünger im Frühjahr ausbringen"
      ],
      "companions": [
        {
          "plant": "Knoblauch",
          "type": "good"
        },
        {
          "plant": "Borretsch",
          "type": "good"
        },
        {
          "plant": "Ringelblume",
          "type": "good"
        },
        {
          "plant": "Tagetes",
          "type": "good"
        },
        {
          "plant": "Schnittlauch",
          "type": "good"
        },
        {
          "plant": "Kartoffeln",
          "type": "avoid"
        },
        {
          "plant": "Erdbeeren",
          "type": "avoid"
        },
        {
          "plant": "Tomaten",
          "type": "avoid"
        }
      ],
      "sowingTime": "N/A (Vermehrung durch Wurzelsprosse oder Stecklinge: Oktober-April)",
      "harvestTime": "Juli-September (Sommerhimbeeren) bzw. August-Oktober (Herbsthimbeeren)"
    }
  },
  {
    "plantName": "Johannisbeere",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Mehltau",
        "Blattfallkrankheit (Anthraknose)",
        "Rost",
        "Grauschimmel (Botrytis)",
        "Welkekrankheit"
      ],
      "pests": [
        "Johannisbeer-Blattlaus",
        "Stachelbeerspinner-Raupe",
        "Johannisbeer-Gallmilbe",
        "Rote Spinne",
        "Kirschfruchtfliege"
      ],
      "careTips": [
        "Johannisbeeren bevorzugen einen sonnigen bis halbschattigen Standort mit nährstoffreichem, feuchtem Boden",
        "Regelmäßiges Gießen ist wichtig, besonders während trockener Perioden und bei der Fruchtbildung",
        "Jährlicher Rückschnitt im Winter fördert die Fruchtbildung und verhindert Vergreisung",
        "Mulchen mit Kompost oder Rindenmulch hält den Boden feucht und unterdrückt Unkraut",
        "Düngung im Frühjahr mit Beerendünger oder Kompost für optimales Wachstum"
      ],
      "companions": [
        {
          "plant": "Stachelbeere",
          "type": "good"
        },
        {
          "plant": "Bohnenkraut",
          "type": "good"
        },
        {
          "plant": "Tomaten",
          "type": "good"
        },
        {
          "plant": "Minze",
          "type": "good"
        },
        {
          "plant": "Ringelblume",
          "type": "good"
        },
        {
          "plant": "Erdbeere",
          "type": "avoid"
        },
        {
          "plant": "Kartoffeln",
          "type": "avoid"
        }
      ],
      "sowingTime": "N/A (Pflanzung von Containerware: Oktober-März)",
      "harvestTime": "Juli-August"
    }
  },
  {
    "plantName": "Stachelbeere",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Echter Mehltau",
        "Stachelbeermehltau",
        "Blattfallkrankheit",
        "Rost",
        "Anthraknose"
      ],
      "pests": [
        "Stachelbeersägewespe",
        "Blattläuse",
        "Spinnmilben",
        "Stachelbeerwickler",
        "Gallmilben"
      ],
      "careTips": [
        "Stachelbeeren bevorzugen einen sonnigen bis halbschattigen Standort mit humusreichem, gut durchlässigem Boden",
        "Regelmäßiges Gießen besonders während trockener Perioden, Staunässe vermeiden",
        "Jährlicher Rückschnitt im Frühjahr fördert Fruchtbildung und Belüftung der Strauchmitte",
        "Mulchen mit Kompost hält den Boden feucht und versorgt die Pflanze mit Nährstoffen",
        "Mehltau-resistente Sorten wie 'Invicta' oder 'Reflava' wählen für weniger Pflanzenschutzaufwand"
      ],
      "companions": [
        {
          "plant": "Tomaten",
          "type": "good"
        },
        {
          "plant": "Ringelblumen",
          "type": "good"
        },
        {
          "plant": "Kapuzinerkresse",
          "type": "good"
        },
        {
          "plant": "Knoblauch",
          "type": "good"
        },
        {
          "plant": "Johannisbeeren",
          "type": "good"
        },
        {
          "plant": "Erdbeeren",
          "type": "good"
        },
        {
          "plant": "Kartoffeln",
          "type": "avoid"
        },
        {
          "plant": "Zwiebeln",
          "type": "avoid"
        }
      ],
      "sowingTime": "N/A (Vermehrung durch Stecklinge oder Ausläufer)",
      "harvestTime": "Juli-August"
    }
  },
  {
    "plantName": "Apfel",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Apfelschorf",
        "Echter Mehltau",
        "Feuerbrand",
        "Obstbaumkrebs",
        "Monilia-Spitzendürre",
        "Rußtau"
      ],
      "pests": [
        "Apfelwickler",
        "Blattläuse",
        "Apfelblütenstecher",
        "Spinnmilben",
        "Schildläuse",
        "Apfelfruchtfliege"
      ],
      "careTips": [
        "Regelmäßiger Winterschnitt fördert Fruchtbildung und Belüftung der Krone",
        "Ausdünnen der Früchte im Juni verbessert Fruchtgröße und verhindert Alternanz",
        "Ausreichend wässern besonders während trockener Sommermonate und bei jungen Bäumen",
        "Organischer Mulch um den Stamm hält Feuchtigkeit und unterdrückt Unkraut",
        "Jährliche Düngung mit reifem Kompost oder Obstbaumdünger im Frühjahr",
        "Regelmäßige Kontrolle auf Krankheiten und Schädlinge durchführen"
      ],
      "companions": [
        {
          "plant": "Knoblauch",
          "type": "good"
        },
        {
          "plant": "Ringelblume",
          "type": "good"
        },
        {
          "plant": "Kapuzinerkresse",
          "type": "good"
        },
        {
          "plant": "Schnittlauch",
          "type": "good"
        },
        {
          "plant": "Bohnenkraut",
          "type": "good"
        },
        {
          "plant": "Walnuss",
          "type": "avoid"
        },
        {
          "plant": "Kartoffeln",
          "type": "avoid"
        },
        {
          "plant": "Gras",
          "type": "avoid"
        }
      ],
      "sowingTime": "Pflanzung von Obstbäumen: November-März (Wurzelware) oder März-Mai (Containerpflanzen)",
      "harvestTime": "August-Oktober, je nach Sorte (Sommergebirge ab August, Winteräpfel ab September-Oktober)"
    }
  },
  {
    "plantName": "Birne",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Feuerbrand",
        "Birnengitterrost",
        "Schorf",
        "Monilia-Spitzendürre",
        "Birnenblattr枯le"
      ],
      "pests": [
        "Birnblattsauger",
        "Birnengallmücke",
        "Obstbaum-Spinnmilbe",
        "Blattläuse",
        "Birnenknospenstecher"
      ],
      "careTips": [
        "Birnen bevorzugen einen sonnigen bis halbschattigen Standort mit nährstoffreichen, tiefgründigen Böden",
        "Regelmäßiger Rückschnitt im Winter fördert die Fruchtqualität und verhindert Verkahlen",
        "Ausreichende Bewässerung während trockener Perioden ist besonders nach der Blüte wichtig",
        "Mulchen im Wurzelbereich schützt vor Austrocknung und Unkraut",
        "Calciummangel vorbeugen durch regelmäßige Düngung"
      ],
      "companions": [
        {
          "plant": "Schwarzer Holunder",
          "type": "good"
        },
        {
          "plant": "Bohnenkraut",
          "type": "good"
        },
        {
          "plant": "Ringelblume",
          "type": "good"
        },
        {
          "plant": "Knoblauch",
          "type": "good"
        },
        {
          "plant": "Walnuss",
          "type": "avoid"
        },
        {
          "plant": "Kartoffeln",
          "type": "avoid"
        }
      ],
      "sowingTime": "N/A (Pflanzung von November bis März)",
      "harvestTime": "August bis Oktober je nach Sorte"
    }
  },
  {
    "plantName": "Pflaume",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Scharkakrankheit",
        "Monilia-Spitzendürre",
        "Schrotschusskrankheit",
        "Blattfleckenkrankheit",
        "Rindenbrand"
      ],
      "pests": [
        "Pflaumenwickler",
        "Blattläuse",
        "Spinnmilben",
        "Pflaumenrost",
        "Bakterienbrand"
      ],
      "careTips": [
        "Regelmäßig ausdünnen, um die Fruchtgröße zu fördern und Überlastung zu vermeiden",
        "Schnittmaßnahmen im Sommer nach der Ernte durchführen, um Wuchskraft zu regulieren",
        "Mulchen mit Grasschnitt oder Kompost, um Feuchtigkeit zu bewahren und Unkraut zu unterdrücken",
        "Ausreichend wässern besonders während der Fruchtentwicklung, Staunässe jedoch vermeiden",
        "Leicht sauren bis neutralen Boden mit guter Drainage bevorzugen"
      ],
      "companions": [
        {
          "plant": "Brennnessel",
          "type": "good"
        },
        {
          "plant": "Knoblauch",
          "type": "good"
        },
        {
          "plant": "Kapuzinerkresse",
          "type": "good"
        },
        {
          "plant": "Beifuß",
          "type": "good"
        },
        {
          "plant": "Schwarzer Holunder",
          "type": "avoid"
        },
        {
          "plant": "Andere Steinobstgehölze in direkter Nachbarschaft",
          "type": "avoid"
        }
      ],
      "sowingTime": "N/A - Pflanzung von Containterware oder wurzelnackten Gehölzen von Oktober bis März, beste Pflanzzeit im Herbst",
      "harvestTime": "Juli bis September, je nach Sorte von früh bis spät reifend"
    }
  },
  {
    "plantName": "Kirsche",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Monilia-Spitzendürre",
        "Schrotschusspilz",
        "Gummifluß",
        "Blattbräune"
      ],
      "pests": [
        "Kirschfruchtfliege",
        "Kirschblattlaus",
        "Spinnmilben",
        "Sauerwurm"
      ],
      "careTips": [
        "Regelmäßiger Winterschnitt fördert Fruchtansatz und Gesundheit",
        "Gleichmäßige Bewässerung besonders während der Fruchtentwicklung",
        "Mulchen mit Grasschnitt oder Kompost zur Feuchtigkeitsspeicherung",
        "Stammschutz vor Sonnenbrand im Winter anbringen",
        "Ausdünnen der Früchte bei übermäßigem Behang für bessere Qualität"
      ],
      "companions": [
        {
          "plant": "Knoblauch",
          "type": "good"
        },
        {
          "plant": "Ringelblume",
          "type": "good"
        },
        {
          "plant": "Borretsch",
          "type": "good"
        },
        {
          "plant": "Walnuss",
          "type": "avoid"
        },
        {
          "plant": "Tomaten",
          "type": "avoid"
        },
        {
          "plant": "Kartoffeln",
          "type": "avoid"
        }
      ],
      "sowingTime": "N/A",
      "harvestTime": "Juli-August (Süßkirschen), Juni-August (Sauerkirschen)"
    }
  },
  {
    "plantName": "Basilikum",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Fusarium-Welke",
        "Grauschimmel (Botrytis)",
        "Blattfleckenkrankheit"
      ],
      "pests": [
        "Blattläuse",
        "Spinnmilben",
        "Weiße Fliegen"
      ],
      "careTips": [
        "Stets warm und vollsonnig halten, mindestens 6 Stunden Sonne täglich",
        "Regelmäßig und gleichmäßig gießen, Staunässe unbedingt vermeiden",
        "Regelmäßig ernten (oberste Blattpaare), um buschiges Wachstum anzuregen"
      ],
      "companions": [
        {
          "plant": "Tomate",
          "type": "good"
        },
        {
          "plant": "Paprika",
          "type": "good"
        },
        {
          "plant": "Oregano",
          "type": "good"
        },
        {
          "plant": "Salbei",
          "type": "avoid"
        },
        {
          "plant": "Thymian",
          "type": "avoid"
        },
        {
          "plant": "Minze",
          "type": "avoid"
        }
      ],
      "sowingTime": "März–Mai (Vorkultur), Mai–Juni (Direktsaat)",
      "harvestTime": "Juni–September"
    }
  },
  {
    "plantName": "Petersilie",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Falscher Mehltau (Peronospora)",
        "Blattfleckenkrankheit (Septoria petroselini)",
        "Wurzelfäule (Pythium)",
        "Grauschimmel (Botrytis cinerea)"
      ],
      "pests": [
        "Möhrenfliege",
        "Blattläuse",
        "Nematoden",
        "Gemeine Spinnmilbe"
      ],
      "careTips": [
        "Samen vor der Aussaat 24 Stunden in Wasser einweichen, um die Keimung zu beschleunigen",
        "Erde gleichmäßig feucht halten, aber Staunässe vermeiden",
        "An einem sonnigen bis halbschattigen Standort anpflanzen",
        "Regelmäßig jäten und den Boden lockern",
        "Immer wieder nachsäen für eine kontinuierliche Ernte"
      ],
      "companions": [
        {
          "plant": "Tomaten",
          "type": "good"
        },
        {
          "plant": "Radieschen",
          "type": "good"
        },
        {
          "plant": "Möhren",
          "type": "good"
        },
        {
          "plant": "Schnittlauch",
          "type": "good"
        },
        {
          "plant": "Salat",
          "type": "avoid"
        },
        {
          "plant": "Lauch",
          "type": "avoid"
        }
      ],
      "sowingTime": "März-Mai oder August-September",
      "harvestTime": "Juni-Oktober"
    }
  },
  {
    "plantName": "Schnittlauch",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Echter Mehltau",
        "Rost",
        "Grauschimmel (Botrytis)",
        "Falscher Mehltau"
      ],
      "pests": [
        "Blattläuse",
        "Thripse",
        "Zwiebelhalsflie",
        "Nematoden"
      ],
      "careTips": [
        "Regelmäßig gießen, dabei Staunässe vermeiden",
        "Nach der Blüte zurückschneiden, um neuen Austrieb zu fördern",
        "Alle 2-3 Jahre die Horste teilen und umpflanzen",
        "Gelegentlich mit organischem Dünger versorgen",
        "Im Winter leicht abdecken für besseren Austrieb im Frühjahr"
      ],
      "companions": [
        {
          "plant": "Karotten",
          "type": "good"
        },
        {
          "plant": "Tomaten",
          "type": "good"
        },
        {
          "plant": "Erdbeeren",
          "type": "good"
        },
        {
          "plant": "Radieschen",
          "type": "good"
        },
        {
          "plant": "Kohl",
          "type": "good"
        },
        {
          "plant": "Erbsen",
          "type": "avoid"
        },
        {
          "plant": "Bohnen",
          "type": "avoid"
        }
      ],
      "sowingTime": "März-Mai",
      "harvestTime": "Mai-Oktober"
    }
  },
  {
    "plantName": "Dill",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Mehltau (Echter Mehltau)",
        "Falscher Mehltau",
        "Blattfleckenkrankheit",
        "Wurzelfäule"
      ],
      "pests": [
        "Blattläuse",
        "Spinnmilben",
        "Dillblattlaus",
        "Möhrenfliege"
      ],
      "careTips": [
        "Sonniger, windgeschützter Standort (Dill ist empfindlich gegen Umknicken)",
        "Feuchter, nährstoffreicher und gut durchlässiger Boden",
        "Regelmäßig gießen, Staunässe vermeiden",
        "Direktsaat ins Freiland (Lichtkeimer – Saatgut nur leicht andrücken)",
        "Nicht pikieren, da Dill tiefe Pfahlwurzeln bildet",
        "Saatabstand ca. 20-30 cm einhalten"
      ],
      "companions": [
        {
          "plant": "Gurken",
          "type": "good"
        },
        {
          "plant": "Kohl",
          "type": "good"
        },
        {
          "plant": "Salat",
          "type": "good"
        },
        {
          "plant": "Zwiebeln",
          "type": "good"
        },
        {
          "plant": "Rote Bete",
          "type": "good"
        },
        {
          "plant": "Fenchel",
          "type": "avoid"
        },
        {
          "plant": "Tomaten",
          "type": "avoid"
        }
      ],
      "sowingTime": "April-Mai (Direktsaat ins Freiland)",
      "harvestTime": "Juni-September (Blätter), August-Oktober (Samen)"
    }
  },
  {
    "plantName": "Koriander",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Echter Mehltau",
        "Falscher Mehltau",
        "Blattfleckenkrankheit",
        "Wurzelfäule"
      ],
      "pests": [
        "Blattläuse",
        "Spinnmilben",
        "Minierfliegen",
        "Schnecken"
      ],
      "careTips": [
        "Standort: Sonnig bis halbschattig, jedoch pralle Mittagssonne im Hochsommer vermeiden",
        "Regelmäßig gießen, Staunässe unbedingt vermeiden – Koriander reagiert empfindlich darauf",
        "Aussaat alle 3–4 Wochen wiederholen für eine kontinuierliche Ernte, da Koriander schnell schosst (bei Hitze)",
        "Boden: Lockere, durchlässige und nährstoffreiche Erde bevorzugen",
        "Bei Trockenheit und Hitze schosst Koriander rasch in Blüte – bei warmer Vorkultur im Haus延迟此过程"
      ],
      "companions": [
        {
          "plant": "Spinat",
          "type": "good"
        },
        {
          "plant": "Tomaten",
          "type": "good"
        },
        {
          "plant": "Salat",
          "type": "good"
        },
        {
          "plant": "Bohnen",
          "type": "good"
        },
        {
          "plant": "Erbsen",
          "type": "good"
        },
        {
          "plant": "Fenchel",
          "type": "avoid"
        },
        {
          "plant": "Dill",
          "type": "avoid"
        }
      ],
      "sowingTime": "März-Mai (Vorkultur) oder April-Mai (Direktsaat ins Freiland)",
      "harvestTime": "Juni-September"
    }
  },
  {
    "plantName": "Minze",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Minzrost",
        "Echter Mehltau",
        "Verticillium-Welke"
      ],
      "pests": [
        "Blattläuse",
        "Spinnmilben",
        "Minz-Erdfloh"
      ],
      "careTips": [
        "Bevorzugt halbschattige bis sonnige Standorte mit feuchtem, nährstoffreichem Boden",
        "Boden gleichmäßig feucht halten, Staunässe jedoch vermeiden",
        "Wuchern durch Kübelhaltung oder Wurzelsperre kontrollieren",
        "Regelmäßig ernten fördert buschigen Wuchs und verhindert Verholzung",
        "Im Frühjahr zurückschneiden für kräftigen Neuaustrieb"
      ],
      "companions": [
        {
          "plant": "Tomaten",
          "type": "good"
        },
        {
          "plant": "Kohl",
          "type": "good"
        },
        {
          "plant": "Erbsen",
          "type": "good"
        },
        {
          "plant": "Petersilie",
          "type": "avoid"
        },
        {
          "plant": "Kamille",
          "type": "avoid"
        }
      ],
      "sowingTime": "März-Mai (Aussaat) oder April-September (Stecklinge/Teilung)",
      "harvestTime": "Juni-September"
    }
  },
  {
    "plantName": "Thymian",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Mehltau",
        "Wurzelfäule"
      ],
      "pests": [
        "Blattläuse",
        "Spinnmilben"
      ],
      "careTips": [
        "Volle Sonne und durchlässigen Boden bieten – Staunässe unbedingt vermeiden",
        "Gießen Sie sparsam und lassen Sie die Erde zwischen den Wassergaben abtrocknen",
        "Nach der Blüte zurückschneiden, um kompakten Wuchs zu fördern und die Pflanze zu verjüngen"
      ],
      "companions": [
        {
          "plant": "Rosmarin",
          "type": "good"
        },
        {
          "plant": "Minze",
          "type": "avoid"
        }
      ],
      "sowingTime": "März-Mai",
      "harvestTime": "Juli-September"
    }
  },
  {
    "plantName": "Rosmarin",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Wurzelfäule",
        "Echter Mehltau",
        "Rosenrost",
        "Grauschimmel"
      ],
      "pests": [
        "Spinnmilben",
        "Blattläuse",
        "Schildläuse",
        "Weiße Fliege"
      ],
      "careTips": [
        "Standort: volle Sonne und geschützt",
        "Boden: durchlässig, sandig-kiesig, mager",
        "Gießen: sparsam, Staunässe unbedingt vermeiden",
        "Überwintern: frostfrei bei 5-15°C oder mit Vlies schützen",
        "Rückschnitt: nach der Blüte leicht zurückschneiden",
        "Düngung: nur sparsam, kaum nötig"
      ],
      "companions": [
        {
          "plant": "Salbei",
          "type": "good"
        },
        {
          "plant": "Thymian",
          "type": "good"
        },
        {
          "plant": "Lavendel",
          "type": "good"
        },
        {
          "plant": "Bohnen",
          "type": "good"
        },
        {
          "plant": "Kohl",
          "type": "good"
        },
        {
          "plant": "Gurken",
          "type": "avoid"
        },
        {
          "plant": "Kürbisse",
          "type": "avoid"
        }
      ],
      "sowingTime": "Februar-März (Vorkultur) oder April-Mai (Direktsaat) – Vermehrung durch Stecklinge empfohlen",
      "harvestTime": "Mai-Oktober – ganzjährig beerntbar"
    }
  },
  {
    "plantName": "Salbei",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Echter Mehltau",
        "Wurzelfäule",
        "Salbeirosette"
      ],
      "pests": [
        "Blattläuse",
        "Spinnmilben",
        "Thripse"
      ],
      "careTips": [
        "Standort: Vollsonnig und warm, mind. 6 Stunden Sonne täglich",
        "Boden: Gut durchlässig, kalkhaltig und mässig nährstoffreich",
        "Giessen: Mässig giessen, Staunässe unbedingt vermeiden",
        "Rückschnitt: Nach der Blüte um ca. ein Drittel zurückschneiden",
        "Winterschutz: Leichter Frostschutz bei strengen Wintern empfohlen",
        "Ernte: Junge Triebe vor der Blüte ernten für besten Geschmack"
      ],
      "companions": [
        {
          "plant": "Rosmarin",
          "type": "good"
        },
        {
          "plant": "Thymian",
          "type": "good"
        },
        {
          "plant": "Oregano",
          "type": "good"
        },
        {
          "plant": "Lavendel",
          "type": "good"
        },
        {
          "plant": "Kohlarten",
          "type": "good"
        },
        {
          "plant": "Gurken",
          "type": "avoid"
        },
        {
          "plant": "Zwiebeln",
          "type": "avoid"
        }
      ],
      "sowingTime": "März-Mai (Vorkultur ab Februar möglich)",
      "harvestTime": "Mai-September (Blätter ganzjährig erntebar)"
    }
  },
  {
    "plantName": "Oregano",
    "articleIds": [],
    "extractedInfo": {
      "diseases": [
        "Echter Mehltau",
        "Wurzelfäule",
        "Rost"
      ],
      "pests": [
        "Blattläuse",
        "Spinnmilben",
        "Thripse"
      ],
      "careTips": [
        "Oregano liebt einen vollsonnigen Standort mit mindestens 6 Stunden direkter Sonneneinstrahlung täglich",
        "Gieße sparsam und vermeide Staunässe – der Boden sollte gut durchlässig sein",
        "Schneide die Triebspitzen regelmäßig zurück, um einen buschigen Wuchs zu fördern und die Blattbildung anzuregen"
      ],
      "companions": [
        {
          "plant": "Tomate",
          "type": "good"
        },
        {
          "plant": "Paprika",
          "type": "good"
        },
        {
          "plant": "Basilikum",
          "type": "good"
        },
        {
          "plant": "Thymian",
          "type": "good"
        },
        {
          "plant": "Majoran",
          "type": "good"
        },
        {
          "plant": "Minze",
          "type": "avoid"
        }
      ],
      "sowingTime": "März-Mai (Vorkultur) oder Mai-Juni (Direktsaat ins Freiland)",
      "harvestTime": "Juli-September – am besten kurz vor oder während der Blüte ernten für maximales Aroma"
    }
  }
];
